# Generated by Django 2.0.2 on 2019-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(max_length=15)),
                ('costo', models.CharField(max_length=15)),
            ],
        ),
    ]
